<?php

namespace Test\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRepository extends EntityRepository
{
}
